package controller;
import implementors.SalesTransactionImplementor; import model.SalesTransaction; import javax.servlet.*; import javax.servlet.annotation.WebServlet; import javax.servlet.http.*; import java.io.IOException;
@WebServlet("/SalesTransactionController")
public class SalesTransactionController extends HttpServlet {
 private static final long serialVersionUID = 1L;
 private SalesTransactionImplementor op=new SalesTransactionImplementor();
 protected void doGet(HttpServletRequest req,HttpServletResponse res)throws ServletException,IOException{String a=req.getParameter("action");if("edit".equals(a)){req.setAttribute("item",op.getById(Integer.parseInt(req.getParameter("id"))));req.getRequestDispatcher("/sales-form.jsp").forward(req,res);}else if("delete".equals(a)){op.delete(Integer.parseInt(req.getParameter("id")));res.sendRedirect("SalesTransactionController");}else{req.setAttribute("items",op.getAll());req.getRequestDispatcher("/sales.jsp").forward(req,res);}}
 protected void doPost(HttpServletRequest req,HttpServletResponse res)throws ServletException,IOException{SalesTransaction x=new SalesTransaction(); String id=req.getParameter("transactionId"); if(id!=null&&!id.isEmpty())x.setTransactionId(Integer.parseInt(id)); x.setProductId(Integer.parseInt(req.getParameter("productId"))); x.setCustomerId(Integer.parseInt(req.getParameter("customerId"))); String sh=req.getParameter("shipmentId"); if(sh==null||sh.trim().isEmpty())x.setShipmentId(null);else x.setShipmentId(Integer.valueOf(sh)); x.setQuantitySold(Double.parseDouble(req.getParameter("quantitySold"))); x.setSalePriceSnapshot(Double.parseDouble(req.getParameter("salePriceSnapshot"))); x.setSaleDate(req.getParameter("saleDate")); if(id!=null&&!id.isEmpty())op.update(x);else op.save(x);res.sendRedirect("SalesTransactionController");}
}
