package implementors;
import db_config.GetConnection; import model.StockUploadLog; import operations.StockUploadLogOperations; import java.sql.*; import java.util.*;
public class StockUploadLogImplementor implements StockUploadLogOperations {
 private StockUploadLog map(ResultSet r)throws SQLException{StockUploadLog x=new StockUploadLog();x.setUploadId(r.getInt("upload_id"));x.setCompanyId(r.getInt("company_id"));x.setUploadedBy(r.getInt("uploaded_by"));x.setCompanyName(r.getString("company_name"));x.setUploadedByName(r.getString("uploaded_by_name"));x.setFileName(r.getString("file_name"));x.setTotalRecords(r.getInt("total_records"));x.setSuccessCount(r.getInt("success_count"));x.setFailureCount(r.getInt("failure_count"));x.setErrorReportPath(r.getString("error_report_path"));x.setUploadedAt(r.getString("uploaded_at"));return x;}
 public List<StockUploadLog> getAll(){List<StockUploadLog>x=new ArrayList<StockUploadLog>();String q="SELECT u.*,c.company_name,us.full_name uploaded_by_name FROM stock_upload_log u JOIN companies c ON u.company_id=c.company_id JOIN users us ON u.uploaded_by=us.user_id ORDER BY u.upload_id DESC";try(Connection c=GetConnection.getConnection();PreparedStatement ps=c.prepareStatement(q);ResultSet r=ps.executeQuery()){while(r.next())x.add(map(r));}catch(Exception e){e.printStackTrace();}return x;}
 public StockUploadLog getById(int id){String q="SELECT u.*,c.company_name,us.full_name uploaded_by_name FROM stock_upload_log u JOIN companies c ON u.company_id=c.company_id JOIN users us ON u.uploaded_by=us.user_id WHERE u.upload_id=?";try(Connection c=GetConnection.getConnection();PreparedStatement ps=c.prepareStatement(q)){ps.setInt(1,id);ResultSet r=ps.executeQuery();if(r.next())return map(r);}catch(Exception e){e.printStackTrace();}return null;}
 public boolean save(StockUploadLog x){String q="INSERT INTO stock_upload_log(company_id,uploaded_by,file_name,total_records,success_count,failure_count,error_report_path) VALUES(?,?,?,?,?,?,?)";try(Connection c=GetConnection.getConnection();PreparedStatement ps=c.prepareStatement(q)){ps.setInt(1,x.getCompanyId());ps.setInt(2,x.getUploadedBy());ps.setString(3,x.getFileName());ps.setInt(4,x.getTotalRecords());ps.setInt(5,x.getSuccessCount());ps.setInt(6,x.getFailureCount());ps.setString(7,x.getErrorReportPath());return ps.executeUpdate()>0;}catch(Exception e){e.printStackTrace();return false;}}
 public boolean update(StockUploadLog x){String q="UPDATE stock_upload_log SET company_id=?,uploaded_by=?,file_name=?,total_records=?,success_count=?,failure_count=?,error_report_path=? WHERE upload_id=?";try(Connection c=GetConnection.getConnection();PreparedStatement ps=c.prepareStatement(q)){ps.setInt(1,x.getCompanyId());ps.setInt(2,x.getUploadedBy());ps.setString(3,x.getFileName());ps.setInt(4,x.getTotalRecords());ps.setInt(5,x.getSuccessCount());ps.setInt(6,x.getFailureCount());ps.setString(7,x.getErrorReportPath());ps.setInt(8,x.getUploadId());return ps.executeUpdate()>0;}catch(Exception e){e.printStackTrace();return false;}}
 public boolean delete(int id){try(Connection c=GetConnection.getConnection();PreparedStatement ps=c.prepareStatement("DELETE FROM stock_upload_log WHERE upload_id=?")){ps.setInt(1,id);return ps.executeUpdate()>0;}catch(Exception e){e.printStackTrace();return false;}}
}
